### ISSUE TITLE
I was able to crash the server with a badly behaving client

### ISSUE THREAD

**Issue by cculianu** [cashshuffle/cashshuffle#14]
This is master latest git.

I was using Electron Cash Cash Shuffle edition and I added code to rapidly hit the server and drop conn about once every second or less.

Here is a log:

```
[Received] packet:<packet:<from_key:<key:"030a6662fcf70ad5a08e96451a477d9b302c7d23535b39f4ae3c72f88d9613d0fb" > registration:<amount:10000 > > >
[Sent] packet:<packet:<session:"x7hewx0IuTpF7smzJw8qub" number:1 > >
[Sent] packet:<packet:<number:1 > >
[Received] packet:<packet:<from_key:<key:"02ee2638b1f083f4c6c27ad05e39fcec9b8f531871f92f769b689baa83e8f07514" > registration:<amount:10000000 > > >
[Sent] packet:<packet:<session:"0jpLQ5pl1ilyK5b30Fb8cl" number:1 > >
[Sent] packet:<packet:<number:1 > >
[Received] packet:<packet:<from_key:<key:"0383d65f13d17aa7b5844f48f14db912bb4c6dc77d3a2098740a5d2533fed5061d" > registration:<amount:1000000 > > >
[Sent] packet:<packet:<session:"Xn1n5f1Jdy50SsjZ7rB9wl" number:1 > >
[Sent] packet:<packet:<number:1 > >
[Received] packet:<packet:<from_key:<key:"0344f5ba13819521672b9384c5d34c5a507468f44967acbd0b5010ac5adc0383fc" > registration:<amount:100000 > > >
[Sent] packet:<packet:<session:"54qvgjK56yXX3CNbVn7q6x" number:1 > >
[Sent] packet:<packet:<number:1 > >
[Received] packet:<packet:<from_key:<key:"034793a644e23dac97ec54af1a2c9b8539d549ae0f4005241d1df578ed45ee5476" > registration:<amount:10000 > > >
[Sent] packet:<packet:<session:"copZSdKUwYIbuhUpGyGsQd" number:1 > >
[Sent] packet:<packet:<number:1 > >
[Received] packet:<packet:<from_key:<key:"03274f061ba6251efd7a919eab2ca62ebc8864a6e13092ce03d310c4e488714e1a" > registration:<amount:10000000 > > >
[Sent] packet:<packet:<session:"dfGPyYK5DecHgcXng30UoP" number:1 > >
[Sent] packet:<packet:<number:1 > >
[Received] packet:<packet:<from_key:<key:"0344c39b03dc65bc082f1eaebbf6ad7c17f73a2e59318e0aeb28f533eed5c640e3" > registration:<amount:1000000 > > >
[Sent] packet:<packet:<session:"kbILKTo5Ed0FwaVJp7xwUX" number:1 > >
[Sent] packet:<packet:<number:1 > >
[Received] packet:<packet:<from_key:<key:"036f7e417be266e526340f9b99efd6cb3a7f3075bec627915bc4cefcd52ca6f1f1" > registration:<amount:100000 > > >
[Sent] packet:<packet:<session:"x0osVYWq4pxcJ1Qc5xuWcm" number:1 > >
[Sent] packet:<packet:<number:1 > >
[Received] packet:<packet:<from_key:<key:"03911cc96a5e56b57e057822092dafdad39cdfd4f8698df8ae9424f6fead0d2542" > registration:<amount:10000 > > >
[Sent] packet:<packet:<session:"27FgT6RbQkbZKg41ZfLY0h" number:1 > >
[Sent] packet:<packet:<number:1 > >
[Received] packet:<packet:<from_key:<key:"039bf37b05cbd1ddc84705c09c7253359dfdc5bb2d5c56e8805b2ef38c76f7e76a" > registration:<amount:10000000 > > >
[Sent] packet:<packet:<session:"br2yWQkQiLktjjyzCM3mIr" number:1 > >
[Sent] packet:<packet:<number:1 > >
[Received] packet:<packet:<from_key:<key:"022881bd33a78681a5eba22ba1e58980ce6328a0e580259420a842537d24ef98dd" > registration:<amount:1000000 > > >
[Sent] packet:<packet:<session:"fSO33mw3SwK0rcfxcgw7Ig" number:1 > >
[Sent] packet:<packet:<number:1 > >
[Received] packet:<packet:<from_key:<key:"020baf5d86403d56be36cde339d79920a40f41abf7c211c4cc5e3cfcd9e9946c5f" > registration:<amount:100000 > > >
[Sent] packet:<packet:<session:"JDVRbL6PK5NLIPu4XyOZD4" number:1 > >
[Sent] packet:<packet:<number:1 > >
[Received] packet:<packet:<from_key:<key:"034b945450f0c777c6ba0fa4c8297e92d9851caf980f687904ea92030069e4f3ee" > registration:<amount:10000 > > >
[Sent] packet:<packet:<session:"UqbXhsqxaYnkPpWFIVVw8B" number:1 > >
[Sent] packet:<packet:<number:1 > >
[Received] packet:<packet:<from_key:<key:"0346e76e34cfb2f2e31ae13018871c548d74710a9ef28acae1e8dbf836664bdc87" > registration:<amount:10000000 > > >
[Sent] packet:<packet:<session:"8iSaplMl2NmzbFWn4sdbuI" number:1 > >
[Sent] packet:<packet:<number:1 > >
[Received] packet:<packet:<from_key:<key:"02dbfaf5cdf6ed1fb6b1ae95efbf1c83b107c773d2c8e496ea0ffe11fba1bb706c" > registration:<amount:1000000 > > >
[Sent] packet:<packet:<session:"mdNvOPz8tSAargo7CtaO0M" number:1 > >
[Sent] packet:<packet:<number:1 > >
[Received] packet:<packet:<from_key:<key:"02b7822f11405484988cdc8972cf4aef24279c2491dcb5b15d4ebf8bf98279c730" > registration:<amount:100000 > > >
[Sent] packet:<packet:<session:"g2FdctBFc7u27zKQnX16tU" number:1 > >
[Sent] packet:<packet:<number:1 > >
[Received] packet:<packet:<from_key:<key:"036f07157ef1ce0fc3ddee8a469254c53e74d7d1c29e7315906ab83e2850431d5b" > registration:<amount:10000 > > >
[Sent] packet:<packet:<session:"KGlgNq23XhKrFGIylmBvTd" number:1 > >
[Error] write tcp 192.168.0.15:9998->192.168.0.23:60215: use of closed network connection
[Received] packet:<packet:<from_key:<key:"035f6d326a2a3eb5bdb62c48176938bd709cee69b8b9be20e112f6232973e0736d" > registration:<amount:10000000 > > >
[Sent] packet:<packet:<session:"J1rrUE8fR0ncqXB7bUW3eU" number:1 > >
[Sent] packet:<packet:<number:1 > >
[Received] packet:<packet:<from_key:<key:"031363646ed09dd6b78b3862e1ad77cbf13dbc1e75e3953891fe82e5d57384b911" > registration:<amount:1000000 > > >
[Sent] packet:<packet:<session:"HTZNkIhnL8pkyNkCCUTEN9" number:1 > >
[Sent] packet:<packet:<number:1 > >
[Received] packet:<packet:<from_key:<key:"02f4f14eaa4a7e5ce9f1e16a0437fb49e1c5c0b6324724a2048c3ff2c7dcff646b" > registration:<amount:100000 > > >
[Sent] packet:<packet:<session:"7iblz4DDXri6c5gUyGh2sJ" number:1 > >
[Sent] packet:<packet:<number:1 > >
[Received] packet:<packet:<from_key:<key:"03ba102f381cff15dc2177d368ba63e30760fca8c34fa4bf42927fcd0599329c37" > registration:<amount:10000 > > >
[Sent] packet:<packet:<session:"VpDiB45l3Idr3ctq2eEIJR" number:2 > >
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x48 pc=0x7221ef]

goroutine 8 [running]:
github.com/cashshuffle/cashshuffle/server.(*packetInfo).processReceivedMessage(0xc0002a4ec0, 0xc000127fa0, 0x0)
        C:/Users/calin/go/src/github.com/cashshuffle/cashshuffle/server/messages.go:52 +0x19f
github.com/cashshuffle/cashshuffle/server.startPacketInfoChan(0xc000022540)
        C:/Users/calin/go/src/github.com/cashshuffle/cashshuffle/server/messages.go:32 +0x6d
created by github.com/cashshuffle/cashshuffle/server.Start
        C:/Users/calin/go/src/github.com/cashshuffle/cashshuffle/server/server.go:33 +0x140

calin@Blackie MINGW64 /c/Users/calin $ 
```

**Comment by zquestz** [comment]
I will work on this tonight, any chance you have a script to simulate this? It would greatly assist my testing. =)

**Comment by cculianu** [comment]
Ah.. I don't.  What I did was just set the "try and start up a new shuffling round" timer to 1 second in the EC client and I manually hit "stop/start" cashshuffle like 40 times in the GUI.

I can write a script but just not right now -- I'm slightly busy trying to focus on the last 100m dash before we test again (I want to do some profiling and other code speedups).

**Comment by cculianu** [comment]
Ok here's something you can do to reproduce it:

1. Clone latest github EC CashShuffle version: https://github.com/clifordsymack/Electron-Cash
2. Run: ./electron-cash -v
3. Enable cashshuffle. Go to Optional Features -> CashShuffle settings to specify your server
4. Open up the "Console Tab" in Electron Cash (View -> Show Console)

Enter the following as 1 line:

```
from PyQt5.QtCore import *; from PyQt5.QtWidgets import *; from PyQt5.QtGui import *; w=[x for x in QApplication.instance().topLevelWidgets() if isinstance(x, QMainWindow)][0]; from electroncash_plugins.shuffle import qt as s; saved=s.start_background_shuffling; s.start_background_shuffling = lambda a,b,period=1,password=None: saved(a,b,1.0,password); import time; import random; 
```

Then enter the following as 2 lines (I don't think cutting and pasting it works)

`while True:`

        w.toggle_cashshuffle(); time.sleep(1.0 + (random.randrange(1,100)/1e3 - 50.0)); print(".")

^^ note the indent there

And hit enter twice...

It should start hammering the server...

**Comment by cculianu** [comment]
Hmm.  Funnily enough running the above exposes a deadlock in a thread in electron cash. :)

So.. it may not really help! Ha!  Still a WIP for me..

**Comment by cculianu** [comment]
Ok well I fixed that deadlock on github latest https://github.com/clifordsymack/Electron-Cash.

Feel free to follow the instructions above (I edited them to be a one-liner).

I managed to reproduce the problem by hammering the server for 10 minutes with that above 1-liner script.

Got the same exact stack trace.

**Comment by alwaysAn0n** [comment]
@GitCash send @cculianu $3 bucks for helping make cashshuffle better!

**Comment by GitCash** [comment]
Hey **cculianu**, user **alwaysAn0n** tipped you **31250 bits** in Bitcoin Cash ( ~ **$3** ).

*[Click here to claim it!](https://gitcash.io/claim/cculianu)*

You can also add the "thumbs down" reaction to **alwaysAn0n**'s comment above to prevent future tips.

**Comment by cculianu** [comment]
Wow @alwaysAn0n !! Thanks! :D

**Comment by zquestz** [comment]
This has been fixed in https://github.com/cashshuffle/cashshuffle/commit/051f8eef12ef82b7daf46127ec916ea27c15d811

I also cut the v0.3.3 release, binaries should be available at https://github.com/cashshuffle/cashshuffle/releases/tag/v0.3.3
